name: flutter_quill_extensions
description: Embed extensions for flutter_quill including image, video, formula and etc.
version: 0.4.0
homepage: https://bulletjournal.us/home/index.html
repository: https://github.com/singerdmx/flutter-quill/tree/master/flutter_quill_extensions

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_quill: ^7.4.1
  image_picker: ^1.0.2
  photo_view: ^0.14.0
  video_player: ^2.7.0
  youtube_player_flutter: ^8.1.2
  math_keyboard: ">=0.2.1"
  string_validator: ^1.0.0
  universal_html: ^2.2.3
  url_launcher: ^6.1.12
  image_network: 2.5.4+1
  #gallery_saver
  path_provider: ^2.1.0
  dio: 5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

# The following section is specific to Flutter packages.
flutter:
